DB_URL=jdbc:postgresql://localhost:5432/gwb
DB_USERNAME=postgres
DB_PASSWORD=Space@2407

DDL_AUTO=update

JWT_SECRET=emKnO4CrT2Xt8Iq1bps7Aj2qyQ783LQc4gPQPx3nV3w=

COOKIE_SECURE=false
COOKIE_SAME_SITE=Lax

STORAGE_ENDPOINT=http://s3.localhost.localstack.cloud:4566
STORAGE_REGION=us-east-1
STORAGE_ACCESS_KEY=test
STORAGE_SECRET_KEY=test
STORAGE_BUCKET=donation-system-files
