spring.application.name=gowaqaf-backend

spring.profiles.active=local

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# JWT Secret Key
jwt.secret=${JWT_SECRET}

# Cookies Setting Configuration
cookie.secure=${COOKIE_SECURE}
cookie.same-site=${COOKIE_SAME_SITE}

# Object Storage Configuration
storage.endpoint=${STORAGE_ENDPOINT}
storage.region=${STORAGE_REGION}
storage.access-key=${STORAGE_ACCESS_KEY}
storage.secret-key=${STORAGE_SECRET_KEY}
storage.bucket=${STORAGE_BUCKET}

# NexGen Payment Gateway API Configuration
nexgen.base-url=${NEXGEN_BASE_URL}
nexgen.api.key=${NEXGEN_API_KEY}
nexgen.api.secret=${NEXGEN_API_SECRET}

nexgen.collection.personal=${NEXGEN_COLLECTION_PERSONAL}
nexgen.collection.merchant=${NEXGEN_COLLECTION_MERCHANT}
nexgen.collection.project=${NEXGEN_COLLECTION_PROJECT}
nexgen.collection.rakan-qr=${NEXGEN_COLLECTION_RAKAN_QR}

# Webhook URL
webhook.base-url=${WEBHOOK_BASE_URL}
