# Database Configuration
DB_URL=jdbc:postgresql://localhost:5432/gwb
DB_USERNAME=postgres
DB_PASSWORD=Space@2407
DDL_AUTO=update

# JWT Secret Key
JWT_SECRET=emKnO4CrT2Xt8Iq1bps7Aj2qyQ783LQc4gPQPx3nV3w=

# Cookies Setting Configuration
COOKIE_SECURE=false
COOKIE_SAME_SITE=Lax

# Object Storage Configuration
STORAGE_ENDPOINT=http://s3.localhost.localstack.cloud:4566
STORAGE_REGION=us-east-1
STORAGE_ACCESS_KEY=test
STORAGE_SECRET_KEY=test
STORAGE_BUCKET=donation-system-files

# NexGen Payment Gateway API Configuration
NEXGEN_BASE_URL=https://dash-nexgen-stg.reliva.com.my
NEXGEN_API_KEY=7a171930-a5c3-439b-b8da-ee297d0b757a
NEXGEN_API_SECRET=lz8EsAYVtM21hx09mHtmdZVA3Vav1VnJ

NEXGEN_COLLECTION_PERSONAL=ZZZZZZZZ
NEXGEN_COLLECTION_MERCHANT=ZZZZZZZZ
NEXGEN_COLLECTION_PROJECT=ZZZZZZZZ
NEXGEN_COLLECTION_RAKAN_QR=ZZZZZZZZ

WEBHOOK_BASE_URL=-
