DB_URL=jdbc:postgresql://postgres:5432/gowaqaf
DB_USERNAME=postgres
DB_PASSWORD=password

DDL_AUTO=create

JWT_SECRET=emKnO4CrT2Xt8Iq1bps7Aj2qyQ783LQc4gPQPx3nV3w=

COOKIE_SECURE=false
COOKIE_SAME_SITE=Lax

STORAGE_ENDPOINT=http://localstack:4566
STORAGE_REGION=us-east-1
STORAGE_ACCESS_KEY=test
STORAGE_SECRET_KEY=test
STORAGE_BUCKET=donation-system-files

# NexGen Payment Gateway API Configuration
NEXGEN_BASE_URL=https://dash-nexgen-stg.reliva.com.my

NEXGEN_COLLECTION_PERSONAL=ISPCFNQA0062
NEXGEN_COLLECTION_MERCHANT=ZZZZZZZZ
NEXGEN_COLLECTION_PROJECT=ZZZZZZZZ
NEXGEN_COLLECTION_RAKAN_QR=ZZZZZZZZ


