
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

jwt.secret=emKnO4CrT2Xt8Iq1bps7Aj2qyQ783LQc4gPQPx3nV3w=

cookie.secure=true
cookie.same-site=Lax

storage.endpoint=http://localhost.localstack.cloud:4566
storage.region=us-east-1
storage.access-key=test
storage.secret-key=test
storage.bucket=donation-system-files
